name: citation_network
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alabaster=0.7.16
  - altair=5.5.0
  - annotated-types=0.7.0
  - anyio=4.7.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.8
  - aws-sdk-cpp=1.11.458
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bibtexparser=1.4.2
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bs4=4.12.3
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cachetools=5.5.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.9.21
  - debugpy=1.8.9
  - decorator=5.1.1
  - deprecated=1.2.15
  - docutils=0.21.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fake-useragent=1.4.0
  - free-proxy=1.1.3
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gitdb=4.0.12
  - gitpython=3.1.44
  - greenlet=3.1.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - httpx-sse=0.4.0
  - hyperframe=6.0.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - krb5=1.21.3
  - langchain=0.3.14
  - langchain-core=0.3.29
  - langchain-text-splitters=0.3.5
  - langgraph=0.2.62
  - langgraph-checkpoint=2.0.9
  - langgraph-sdk=0.1.51
  - langsmith=0.2.10
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libdeflate=1.23
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libparquet=18.1.0
  - libpng=1.6.45
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lxml=5.3.0
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2024.2.2
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - narwhals=1.21.1
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - orc=2.0.3
  - orjson=3.10.14
  - outcome=1.3.0.post0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - propcache=0.2.1
  - protobuf=5.28.3
  - psutil=6.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pycparser=2.22
  - pydantic=2.10.5
  - pydantic-core=2.27.2
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pywin32=307
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - referencing=0.35.1
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rpds-py=0.22.3
  - scholarly=1.7.11
  - selenium=4.27.1
  - selenium-manager=4.27.0
  - setuptools=75.6.0
  - six=1.17.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.4.7
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.37
  - stack_data=0.6.3
  - streamlit=1.41.1
  - tbb=2021.13.0
  - tenacity=9.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trio=0.27.0
  - trio-websocket=0.11.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - tzlocal=5.2
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webdriver-manager=4.0.2
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - wsproto=1.2.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - dataclasses-json==0.6.7
      - filetype==1.2.0
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.158.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - httplib2==0.22.0
      - langchain-community==0.3.14
      - langchain-google-genai==2.0.8
      - marshmallow==3.25.0
      - mypy-extensions==1.0.0
      - neo4j==5.27.0
      - proto-plus==1.25.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic-settings==2.7.1
      - rsa==4.9
      - typing-inspect==0.9.0
      - uritemplate==4.1.1
